ros_figaro/Normal2 prior_w0
ros_figaro/Normal2 prior_w1
ros_figaro/DataPoint2 observation
---
ros_figaro/Normal2 posterior_w0
ros_figaro/Normal2 posterior_w1
ros_figaro/ImportanceSample[] samples_w0
ros_figaro/ImportanceSample[] samples_w1
